### ISSUE TITLE
THREDDS 5.5 SNAPSHOT - Not supporting CRS EPSG:3857

### ISSUE THREAD

**Issue by ashokgj** [Unidata/tds#455]
USING: THREDDS Data Server 5.5 (released on 2024-01-19)(Beta)
Environment: Linux
JAVA: JDK 11

The new version of THREDDS isn't supporting the CRS EPSG:3857. Has support for this been permanently disabled? Or is it a problem with my instance? It used to  work on previous versions.

https://climatedata.worldbank.org/thredds/wms/CRM/cmip6-x0.25/tas/ensemble-all-ssp585/anomaly-tas-annual-mean_cmip6-x0.25_ensemble-all-ssp585_climatology_median_2080-2099.nc?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=anomaly-tas-annual-mean&TILED=true&STYLES=raster%2Fcckp-GHRSST_anomaly&COLORSCALERANGE=-2%2C16&NUMCOLORBANDS=256&TIME=2080-07-01T00%3A00%3A00.000Z&CRS=EPSG%3A3857&WIDTH=256&HEIGHT=256&BBOX=0%2C-10018754.17139462%2C10018754.171394622%2C1.862645149230957e-9

Error Message:

<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="InvalidCRS"> The CRS EPSG:3857 is not supported by this server Cause: No ?CoordinateReferenceSystem? object found for code ?3857?. However only a subset of the EPSG geodetic dataset has been queried. See http://sis.apache.org/epsg.html for instruction about how to install the full EPSG database. </ServiceException>
</ServiceExceptionReport>

**Comment by tdrwenski** [comment]
Thanks for reporting this. I believe this is a regression that the epsg database is not getting loaded. Are you seeing an error in your threddsServlet.log like:
```
ERROR - uk.ac.rdg.resc.edal.util.GISUtils - Problem creating EPSG database.  Reprojection will not work
```
We should have a fix shortly.

**Comment by tdrwenski** [comment]
This should be resolved in the latest 5.5 snapshot. Let us know if you still have issues!

**Comment by BMarques** [comment]
I installed the snapshot from today and I'm getting exactly the same issue

**Comment by tdrwenski** [comment]
@BMarques, can you open a new issue for your problem? Would be useful if you could include details about your environment as well as your `serverStartup.log` file.

**Comment by BMarques** [comment]
Unfortunately i'm no longer able to reproduce the error, for unrelated reasons, I needed to reinstall Thredds and Apache Tomcat, but now I don't have the error any longer. 

I'm now on Tomcat 9, I had version 8.5.98 before. Not sure if it's the reason, but it's ok now.

**Comment by PeriklisICES** [comment]
I just installed TDS 5.5 (2024-07-16) and I am getting this.
I am on windows. Tomcat 9. Open jdk-17.0.2
I am upgrading from version 5.4.

I do get this error:
`ERROR - uk.ac.rdg.resc.edal.util.GISUtils - Problem creating EPSG database.  Reprojection will not work
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/content/thredds/cache/edal-java/epsg//.h2/epsg.db" [50000-210]`

**Comment by tdrwenski** [comment]
Hi @PeriklisICES, it looks like the file path for the epsg database is incorrect in that error message-- either due to the change in this issue or possibly due your content root path being formatted incorrectly.  What do you have your content root path (`-Dtds.content.root.path=`) set to in your setenv.bat file? Is the TDS starting up and working other than WMS and the epsg database?

**Comment by PeriklisICES** [comment]
Thanks @tdrwenski for looking into this.
I am setting my env vars through Tomcat. I have set `-Dtds.content.root.path=D:\content`
Which seems to work just fine with TDS 5.4

Other than the EPSG db, everything seems to be running fine. My content structure looks correct and WMS works in Godiva preview in 4326.

**Comment by tdrwenski** [comment]
Thanks @PeriklisICES! Can you test if the EPSG db works for you now with the latest 5.6-SNAPSHOT (which you can download [here](https://downloads.unidata.ucar.edu/tds/5.6/thredds-5.6-SNAPSHOT.war))? I think it should be fixed but I don't have a windows machine to test on so would appreciate if you could let me know!

**Comment by tdrwenski** [comment]
@PeriklisICES have you had a chance to test with the latest snapshot?

**Comment by PeriklisICES** [comment]
Sorry @tdrwenski for the delay, I got caught up with other things. I tried to use the snapshot but I didn't manage to even start it. I am getting a `org.apache.catalina.core.StandardContext start SEVERE: Context [/thredds] startup failed due to previous errors`
and the context specific logs are empty. Maybe my Java is not compatible? I have Open jdk-17.0.2. I will try other versions when I find some time.

Note that the error in relation to the EPSG was in a 5.5 version. So if the same fix can be ported into a 5.5 snapshot, I could try that.

Thanks a lot for the efforts!

**Comment by tdrwenski** [comment]
Hi @PeriklisICES, sorry, I should have mentioned that the 5.6-SNAPSHOT [requires](https://docs.unidata.ucar.edu/tds/5.6/userguide/install_java_tomcat.html) tomcat 10, JDK 17, and extra JVM arguments given here in [CHRONICLE_CACHE](https://docs.unidata.ucar.edu/tds/5.6/userguide/running_tomcat.html#setting-java_home-java_opts-catalina_home-catalina_base-and-content_root).

**Comment by PeriklisICES** [comment]
Ok, I did set up the 5.6 snapshot properly now with tomcat 10 and it worked. Thanks! But the EPSG error is back. It seems that the path is still not properly parsed:
`ERROR - uk.ac.rdg.resc.edal.util.GISUtils - Problem creating EPSG database.  Reprojection will not work
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/content/thredds/cache/edal-java/epsg//.h2/epsg.db" [50000-210]`

My Java options:
```
-Dcatalina.home=C:\Program Files\Apache Software Foundation\Tomcat 10.1
-Dcatalina.base=C:\Program Files\Apache Software Foundation\Tomcat 10.1
-Djava.io.tmpdir=C:\Program Files\Apache Software Foundation\Tomcat 10.1\temp
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-Djava.util.logging.config.file=C:\Program Files\Apache Software Foundation\Tomcat 10.1\conf\logging.properties
-Dtds.content.root.path=D:\content
-Djava.awt.headless=true
-Djava.util.prefs.systemRoot=D:\content\thredds\javaUtilPrefs
-Djava.util.prefs.userRoot=D:\content\thredds\javaUtilPrefs

```

If you there is another snapshot, I can more easily test it now as I have the setup ready.
Thanks again.
